//GET EXPENSES FROM BACKEND
export const GET_EXPENSES_STARTED = "GET_EXPENSES_STARTED";
export const GET_EXPENSES_SUCESS = "GET_EXPENSES_SUCESS";
export const GET_EXPENSES_FAILURE = "GET_EXPENSES_FAILURE";

//GET CATEGORIES FROM BACKEND
export const GET_CATEGORIES_STARTED = "GET_CATEGORIES_STARTED";
export const GET_CATEGORIES_SUCESS = "GET_CATEGORIES_SUCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

//POST NEW EXPENSE TO BACKEND
export const ADD_EXPENSE_STARTED = "ADD_EXPENSE_STARTED";
export const ADD_EXPENSE_SUCESS = "ADD_EXPENSE_SUCESS";
export const ADD_EXPENSE_FAILURE = "ADD_EXPENSE_FAILURE";

//PATCH A EXISTING EXPENSE
export const EDIT_EXPENSE_STARTED = "EDIT_EXPENSE_STARTED";
export const EDIT_EXPENSE_SUCCESS = "EDIT_EXPENSE_SUCCESS";
export const EDIT_EXPENSE_FAILURE = "EDIT_EXPENSE_FAILURE";

//POST NEW CATEGORY TO BACKEND
export const ADD_CATEGORY_STARTED = "ADD_CATEGORY_STARTED";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

//GET BUDGET
export const GET_BUDGET_STARTED = "GET_BUDGET_STARTED";
export const GET_BUDGET_SUCCESS = "GET_BUDGET_SUCCESS";
export const GET_BUDGET_FAILURE = "GET_BUDGET_FAILURE";

// POST New Budget

export const CREATE_BUDGET_STARTED = "CREATE_BUDGET_STARTED";
export const CREATE_BUDGET_SUCCESS = "CREATE_BUDGET_SUCCESS";
export const CREATE_BUDGET_FAILURE = "CREATE_BUDGET_FAILURE";

//PATCH Existing BUDGET

export const EDIT_BUDGET_STARTED = "EDIT_BUDGET_STARTED";
export const EDIT_BUDGET_SUCCESS = "EDIT_BUDGET_SUCCESS";
export const EDIT_BUDGET_FAILURE = "EDIT_BUDGET_FAILURE";

//DELETE CATEGORY

export const DELETE_CATEGORY_STARTED = "DELETE_CATEGORY_STARTED";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";
